import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main 
      className={styles.main}>

       <h1 
       className={styles.title}>Welcome to Week8!!</h1>


       <section 
       className={styles.contents}>

          <h2 
          className={styles.example_title}>Here's Links for Examples:</h2>

         <div 
         className={styles.links}>

         <div><Link href="/useEffectOne">useEffectOne</Link></div>
         <div><Link href="/useEffectTwo">useEffectTwo</Link></div>
         <div><Link href="/useEffectThree">useEffectThree</Link></div>
         <div><Link href="/carouselPage">CarouselPage</Link></div>

         </div>
         

      </section>
       
      </main>
    </>
  )
}
